/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2020-05-28 14:58:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kitchendisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("            var connectionOpen = false; //Global variables\r\n");
      out.write("            var nextOrder = 1; //Increment afer every response to start polling for next response. Fetches already present orders quickly\r\n");
      out.write("            \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t// and waits for new one.\r\n");
      out.write("            \r\n");
      out.write("            //GetOrders gets called again and again.\r\n");
      out.write("            \r\n");
      out.write("            function getOrders(){   // Opening connection to server\r\n");
      out.write("            \t\r\n");
      out.write("                if(!connectionOpen){ // Polling every 500ms to check if connection is open. If open, doesn't do anything. \r\n");
      out.write("                \t\r\n");
      out.write("                \tconnectionOpen = true;  // If connection closed, fires a new connection and starts polling again, till receiving response.\r\n");
      out.write("                \t\r\n");
      out.write("                    var xmlhttp = new XMLHttpRequest();\r\n");
      out.write("                    xmlhttp.onreadystatechange=function(){\r\n");
      out.write("                    \t\t\t\t\t\t\t\t//status==200 to avoid timeout response and check if there is an actual response\r\n");
      out.write("                        if (xmlhttp.readyState==4 && xmlhttp.status==200) {  //Closing connection if received response.\r\n");
      out.write("                        \tconnectionOpen = false;\r\n");
      out.write("                        \tnextOrder++; //To retrieve next order\r\n");
      out.write("                            var ordersDiv = document.getElementById(\"orders\");\r\n");
      out.write("                            ordersDiv.innerHTML = xmlhttp.responseText + ordersDiv.innerHTML;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\t\t\t\t\t\t\t\t\t\t//parameter 'size' taken by servlet in server side.\r\n");
      out.write("                    xmlhttp.open(\"GET\", \"/kitchenAsyncServlet?size=\" + nextOrder, true);\r\n");
      out.write("                    xmlhttp.send();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            setInterval(getOrders, 500);  // Polling every 500ms if connection is open. \r\n");
      out.write("        </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>Ricky's Restaurant - Live orders</h1>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"orders\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
